// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: auth/v1/auther.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_NormalUser  Role = 0 //正常用户
	Role_Merchant    Role = 1 //商家
	Role_BlackLister Role = 2
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "NormalUser",
		1: "Merchant",
		2: "BlackLister",
	}
	Role_value = map[string]int32{
		"NormalUser":  0,
		"Merchant":    1,
		"BlackLister": 2,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_v1_auther_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_auth_v1_auther_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_auth_v1_auther_proto_rawDescGZIP(), []int{0}
}

type Obj int32

const (
	Obj_User          Obj = 0
	Obj_Item          Obj = 1
	Obj_Order         Obj = 2
	Obj_PayService    Obj = 3
	Obj_Shopping_cart Obj = 4
)

// Enum value maps for Obj.
var (
	Obj_name = map[int32]string{
		0: "User",
		1: "Item",
		2: "Order",
		3: "PayService",
		4: "Shopping_cart",
	}
	Obj_value = map[string]int32{
		"User":          0,
		"Item":          1,
		"Order":         2,
		"PayService":    3,
		"Shopping_cart": 4,
	}
)

func (x Obj) Enum() *Obj {
	p := new(Obj)
	*p = x
	return p
}

func (x Obj) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Obj) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_v1_auther_proto_enumTypes[1].Descriptor()
}

func (Obj) Type() protoreflect.EnumType {
	return &file_auth_v1_auther_proto_enumTypes[1]
}

func (x Obj) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Obj.Descriptor instead.
func (Obj) EnumDescriptor() ([]byte, []int) {
	return file_auth_v1_auther_proto_rawDescGZIP(), []int{1}
}

type Act int32

const (
	Act_Create Act = 0
	Act_Login  Act = 1
	Act_Logout Act = 2
	Act_Update Act = 3
	Act_Delete Act = 4
	Act_Get    Act = 5
	Act_Clear  Act = 6
	Act_Pay    Act = 7
	Act_Cancel Act = 8
	Act_Settle Act = 9
)

// Enum value maps for Act.
var (
	Act_name = map[int32]string{
		0: "Create",
		1: "Login",
		2: "Logout",
		3: "Update",
		4: "Delete",
		5: "Get",
		6: "Clear",
		7: "Pay",
		8: "Cancel",
		9: "Settle",
	}
	Act_value = map[string]int32{
		"Create": 0,
		"Login":  1,
		"Logout": 2,
		"Update": 3,
		"Delete": 4,
		"Get":    5,
		"Clear":  6,
		"Pay":    7,
		"Cancel": 8,
		"Settle": 9,
	}
)

func (x Act) Enum() *Act {
	p := new(Act)
	*p = x
	return p
}

func (x Act) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Act) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_v1_auther_proto_enumTypes[2].Descriptor()
}

func (Act) Type() protoreflect.EnumType {
	return &file_auth_v1_auther_proto_enumTypes[2]
}

func (x Act) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Act.Descriptor instead.
func (Act) EnumDescriptor() ([]byte, []int) {
	return file_auth_v1_auther_proto_rawDescGZIP(), []int{2}
}

type DeliverTokenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *DeliverTokenReq) Reset() {
	*x = DeliverTokenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_v1_auther_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeliverTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverTokenReq) ProtoMessage() {}

func (x *DeliverTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auther_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverTokenReq.ProtoReflect.Descriptor instead.
func (*DeliverTokenReq) Descriptor() ([]byte, []int) {
	return file_auth_v1_auther_proto_rawDescGZIP(), []int{0}
}

func (x *DeliverTokenReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type VerifyTokenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token *string `protobuf:"bytes,1,opt,name=token,proto3,oneof" json:"token,omitempty"`
	Obj   Obj     `protobuf:"varint,2,opt,name=obj,proto3,enum=auth.v1.Obj" json:"obj,omitempty"`
	Act   Act     `protobuf:"varint,3,opt,name=act,proto3,enum=auth.v1.Act" json:"act,omitempty"`
}

func (x *VerifyTokenReq) Reset() {
	*x = VerifyTokenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_v1_auther_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenReq) ProtoMessage() {}

func (x *VerifyTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auther_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenReq.ProtoReflect.Descriptor instead.
func (*VerifyTokenReq) Descriptor() ([]byte, []int) {
	return file_auth_v1_auther_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyTokenReq) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

func (x *VerifyTokenReq) GetObj() Obj {
	if x != nil {
		return x.Obj
	}
	return Obj_User
}

func (x *VerifyTokenReq) GetAct() Act {
	if x != nil {
		return x.Act
	}
	return Act_Create
}

type AssignRoleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role   Role  `protobuf:"varint,2,opt,name=role,proto3,enum=auth.v1.Role" json:"role,omitempty"`
}

func (x *AssignRoleReq) Reset() {
	*x = AssignRoleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_v1_auther_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleReq) ProtoMessage() {}

func (x *AssignRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auther_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleReq.ProtoReflect.Descriptor instead.
func (*AssignRoleReq) Descriptor() ([]byte, []int) {
	return file_auth_v1_auther_proto_rawDescGZIP(), []int{2}
}

func (x *AssignRoleReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AssignRoleReq) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_NormalUser
}

type RemoveRoleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role   Role  `protobuf:"varint,2,opt,name=role,proto3,enum=auth.v1.Role" json:"role,omitempty"`
}

func (x *RemoveRoleReq) Reset() {
	*x = RemoveRoleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_v1_auther_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRoleReq) ProtoMessage() {}

func (x *RemoveRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auther_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRoleReq.ProtoReflect.Descriptor instead.
func (*RemoveRoleReq) Descriptor() ([]byte, []int) {
	return file_auth_v1_auther_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveRoleReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RemoveRoleReq) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_NormalUser
}

type DeliveryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *DeliveryResp) Reset() {
	*x = DeliveryResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_v1_auther_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeliveryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryResp) ProtoMessage() {}

func (x *DeliveryResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auther_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryResp.ProtoReflect.Descriptor instead.
func (*DeliveryResp) Descriptor() ([]byte, []int) {
	return file_auth_v1_auther_proto_rawDescGZIP(), []int{4}
}

func (x *DeliveryResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type VerifyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res bool `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *VerifyResp) Reset() {
	*x = VerifyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_v1_auther_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResp) ProtoMessage() {}

func (x *VerifyResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auther_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResp.ProtoReflect.Descriptor instead.
func (*VerifyResp) Descriptor() ([]byte, []int) {
	return file_auth_v1_auther_proto_rawDescGZIP(), []int{5}
}

func (x *VerifyResp) GetRes() bool {
	if x != nil {
		return x.Res
	}
	return false
}

type AssignResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res bool `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *AssignResp) Reset() {
	*x = AssignResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_v1_auther_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignResp) ProtoMessage() {}

func (x *AssignResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auther_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignResp.ProtoReflect.Descriptor instead.
func (*AssignResp) Descriptor() ([]byte, []int) {
	return file_auth_v1_auther_proto_rawDescGZIP(), []int{6}
}

func (x *AssignResp) GetRes() bool {
	if x != nil {
		return x.Res
	}
	return false
}

type RemoveResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res bool `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *RemoveResp) Reset() {
	*x = RemoveResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_v1_auther_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResp) ProtoMessage() {}

func (x *RemoveResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auther_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResp.ProtoReflect.Descriptor instead.
func (*RemoveResp) Descriptor() ([]byte, []int) {
	return file_auth_v1_auther_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveResp) GetRes() bool {
	if x != nil {
		return x.Res
	}
	return false
}

var File_auth_v1_auther_proto protoreflect.FileDescriptor

var file_auth_v1_auther_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x22,
	0x2a, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52,
	0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x75, 0x0a, 0x0e, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x1e, 0x0a, 0x03, 0x6f, 0x62, 0x6a, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e,
	0x4f, 0x62, 0x6a, 0x52, 0x03, 0x6f, 0x62, 0x6a, 0x12, 0x1e, 0x0a, 0x03, 0x61, 0x63, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e,
	0x41, 0x63, 0x74, 0x52, 0x03, 0x61, 0x63, 0x74, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x22, 0x4b, 0x0a, 0x0d, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x52, 0x6f, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x04,
	0x72, 0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x61, 0x75, 0x74,
	0x68, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x22,
	0x4b, 0x0a, 0x0d, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x04, 0x72, 0x6f, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x22, 0x24, 0x0a, 0x0c,
	0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x22, 0x1e, 0x0a, 0x0a, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x72,
	0x65, 0x73, 0x22, 0x1e, 0x0a, 0x0a, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x72,
	0x65, 0x73, 0x22, 0x1e, 0x0a, 0x0a, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x72,
	0x65, 0x73, 0x2a, 0x35, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x4e, 0x6f,
	0x72, 0x6d, 0x61, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x65,
	0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x42, 0x6c, 0x61, 0x63,
	0x6b, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x72, 0x10, 0x02, 0x2a, 0x47, 0x0a, 0x03, 0x4f, 0x62, 0x6a,
	0x12, 0x08, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x74,
	0x65, 0x6d, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x10, 0x02, 0x12,
	0x0e, 0x0a, 0x0a, 0x50, 0x61, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x10, 0x03, 0x12,
	0x11, 0x0a, 0x0d, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x63, 0x61, 0x72, 0x74,
	0x10, 0x04, 0x2a, 0x75, 0x0a, 0x03, 0x41, 0x63, 0x74, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x10, 0x01,
	0x12, 0x0a, 0x0a, 0x06, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x10, 0x04, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x10, 0x05, 0x12, 0x09, 0x0a,
	0x05, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x10, 0x06, 0x12, 0x07, 0x0a, 0x03, 0x50, 0x61, 0x79, 0x10,
	0x07, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x10, 0x08, 0x12, 0x0a, 0x0a,
	0x06, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x10, 0x09, 0x32, 0x93, 0x02, 0x0a, 0x0b, 0x41, 0x75,
	0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x11, 0x44, 0x65, 0x6c,
	0x69, 0x76, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x79, 0x52, 0x50, 0x43, 0x12, 0x18,
	0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e,
	0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x00, 0x12, 0x42, 0x0a, 0x10, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x42, 0x79, 0x52, 0x50, 0x43, 0x12, 0x17, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x13,
	0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0a, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x52,
	0x6f, 0x6c, 0x65, 0x12, 0x16, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x73,
	0x73, 0x69, 0x67, 0x6e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x61, 0x75,
	0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0a, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x6f, 0x6c, 0x65,
	0x12, 0x16, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e,
	0x76, 0x31, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42,
	0x19, 0x5a, 0x17, 0x61, 0x75, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_auth_v1_auther_proto_rawDescOnce sync.Once
	file_auth_v1_auther_proto_rawDescData = file_auth_v1_auther_proto_rawDesc
)

func file_auth_v1_auther_proto_rawDescGZIP() []byte {
	file_auth_v1_auther_proto_rawDescOnce.Do(func() {
		file_auth_v1_auther_proto_rawDescData = protoimpl.X.CompressGZIP(file_auth_v1_auther_proto_rawDescData)
	})
	return file_auth_v1_auther_proto_rawDescData
}

var file_auth_v1_auther_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_auth_v1_auther_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_auth_v1_auther_proto_goTypes = []any{
	(Role)(0),               // 0: auth.v1.Role
	(Obj)(0),                // 1: auth.v1.Obj
	(Act)(0),                // 2: auth.v1.Act
	(*DeliverTokenReq)(nil), // 3: auth.v1.DeliverTokenReq
	(*VerifyTokenReq)(nil),  // 4: auth.v1.VerifyTokenReq
	(*AssignRoleReq)(nil),   // 5: auth.v1.AssignRoleReq
	(*RemoveRoleReq)(nil),   // 6: auth.v1.RemoveRoleReq
	(*DeliveryResp)(nil),    // 7: auth.v1.DeliveryResp
	(*VerifyResp)(nil),      // 8: auth.v1.VerifyResp
	(*AssignResp)(nil),      // 9: auth.v1.AssignResp
	(*RemoveResp)(nil),      // 10: auth.v1.RemoveResp
}
var file_auth_v1_auther_proto_depIdxs = []int32{
	1,  // 0: auth.v1.VerifyTokenReq.obj:type_name -> auth.v1.Obj
	2,  // 1: auth.v1.VerifyTokenReq.act:type_name -> auth.v1.Act
	0,  // 2: auth.v1.AssignRoleReq.role:type_name -> auth.v1.Role
	0,  // 3: auth.v1.RemoveRoleReq.role:type_name -> auth.v1.Role
	3,  // 4: auth.v1.AuthService.DeliverTokenByRPC:input_type -> auth.v1.DeliverTokenReq
	4,  // 5: auth.v1.AuthService.VerifyTokenByRPC:input_type -> auth.v1.VerifyTokenReq
	5,  // 6: auth.v1.AuthService.AssignRole:input_type -> auth.v1.AssignRoleReq
	6,  // 7: auth.v1.AuthService.RemoveRole:input_type -> auth.v1.RemoveRoleReq
	7,  // 8: auth.v1.AuthService.DeliverTokenByRPC:output_type -> auth.v1.DeliveryResp
	8,  // 9: auth.v1.AuthService.VerifyTokenByRPC:output_type -> auth.v1.VerifyResp
	9,  // 10: auth.v1.AuthService.AssignRole:output_type -> auth.v1.AssignResp
	10, // 11: auth.v1.AuthService.RemoveRole:output_type -> auth.v1.RemoveResp
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_auth_v1_auther_proto_init() }
func file_auth_v1_auther_proto_init() {
	if File_auth_v1_auther_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_auth_v1_auther_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*DeliverTokenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_v1_auther_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*VerifyTokenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_v1_auther_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AssignRoleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_v1_auther_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*RemoveRoleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_v1_auther_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*DeliveryResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_v1_auther_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*VerifyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_v1_auther_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*AssignResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_v1_auther_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*RemoveResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_auth_v1_auther_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_auth_v1_auther_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_auther_proto_goTypes,
		DependencyIndexes: file_auth_v1_auther_proto_depIdxs,
		EnumInfos:         file_auth_v1_auther_proto_enumTypes,
		MessageInfos:      file_auth_v1_auther_proto_msgTypes,
	}.Build()
	File_auth_v1_auther_proto = out.File
	file_auth_v1_auther_proto_rawDesc = nil
	file_auth_v1_auther_proto_goTypes = nil
	file_auth_v1_auther_proto_depIdxs = nil
}
